# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-16 22:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieInfo',
            fields=[
                ('m_id', models.AutoField(primary_key=True, serialize=False)),
                ('m_name', models.CharField(max_length=100)),
                ('m_type', models.CharField(blank=True, max_length=100, null=True)),
                ('m_country', models.CharField(blank=True, max_length=50, null=True)),
                ('m_year', models.CharField(blank=True, max_length=100, null=True)),
                ('post_url', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'movie_info',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Sentimentclassify',
            fields=[
                ('index', models.AutoField(primary_key=True, serialize=False)),
                ('bad_count', models.IntegerField(blank=True, null=True)),
                ('middle_count', models.IntegerField(blank=True, null=True)),
                ('good_count', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'sentimentClassify',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ShortComments',
            fields=[
                ('c_id', models.AutoField(primary_key=True, serialize=False)),
                ('comments', models.CharField(blank=True, max_length=1000, null=True)),
                ('vote_num', models.CharField(blank=True, max_length=10, null=True)),
                ('time', models.CharField(blank=True, max_length=20, null=True)),
                ('star', models.IntegerField(blank=True, null=True)),
                ('sentiment', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'short_comments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('u_id', models.AutoField(primary_key=True, serialize=False)),
                ('u_name', models.CharField(blank=True, max_length=50, null=True)),
                ('u_url', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'user',
                'managed': False,
            },
        ),
    ]
